version: 2
jobs:
  test:
    docker:
      - image: ianwalter/puppeteer:latest
    steps:
      - checkout
      - run:
          name: Install Node Modules
          command: npm install
      - run:
          name: Execute ESlint Check
          command: npm run lint
      - run:
          name: Execute TSC Check
          command: npm run tsc
      - run:
          name: Prepare sample .env file
          command: echo "TRUSK_API_BASE_URL=https://staging-01-api.trusk.com\nTRUSK_BUSINESS_BASE_URL=https://staging-01-pro.trusk.com" > .env
      - run:
          name: Test (Jest)
          command: npx jest
      - run:
          name: Test (Cucumber)
          command: npx cucumber-js
workflows:
  version: 2
  test:
    jobs:
      - test